// Package condapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package condapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AppointmentStatus.
const (
	Cancelled AppointmentStatus = "cancelled"
	Completed AppointmentStatus = "completed"
	Denied    AppointmentStatus = "denied"
	Requested AppointmentStatus = "requested"
	Scheduled AppointmentStatus = "scheduled"
)

// Defines values for AppointmentType.
const (
	RegularCheck AppointmentType = "regular_check"
)

// AppointmentDisplay Represents an appointment view relevant to a condition.
type AppointmentDisplay struct {
	AppointmentDateTime time.Time          `json:"appointmentDateTime"`
	DoctorName          string             `json:"doctorName"`
	Id                  openapi_types.UUID `json:"id"`
	PatientName         string             `json:"patientName"`
	Status              AppointmentStatus  `json:"status"`
	Type                AppointmentType    `json:"type"`
}

// AppointmentStatus defines model for AppointmentStatus.
type AppointmentStatus string

// AppointmentType defines model for AppointmentType.
type AppointmentType string

// Condition defines model for Condition.
type Condition struct {
	Appointments    *[]AppointmentDisplay `json:"appointments,omitempty"`
	AppointmentsIds *[]openapi_types.UUID `json:"appointmentsIds,omitempty"`
	End             *time.Time            `json:"end"`
	Id              *openapi_types.UUID   `json:"id,omitempty"`
	Name            string                `json:"name"`
	Start           time.Time             `json:"start"`
}

// ConditionDisplay Basic info about a patient's condition.
type ConditionDisplay struct {
	AppointmentsIds *[]openapi_types.UUID `json:"appointmentsIds,omitempty"`
	End             *time.Time            `json:"end"`
	Id              *openapi_types.UUID   `json:"id,omitempty"`
	Name            string                `json:"name"`
	Start           time.Time             `json:"start"`
}

// ErrorDetail Standardized error details (RFC 9457).
type ErrorDetail struct {
	Code                 string                 `json:"code"`
	Detail               string                 `json:"detail"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NewCondition defines model for NewCondition.
type NewCondition struct {
	AppointmentsIds *[]openapi_types.UUID `json:"appointmentsIds,omitempty"`
	End             *time.Time            `json:"end"`
	Name            string                `json:"name"`
	PatientId       openapi_types.UUID    `json:"patientId"`
	Start           time.Time             `json:"start"`
}

// UpdateCondition defines model for UpdateCondition.
type UpdateCondition struct {
	AppointmentsIds *[]openapi_types.UUID `json:"appointmentsIds,omitempty"`
	End             *time.Time            `json:"end"`
	Name            *string               `json:"name,omitempty"`
	Start           *time.Time            `json:"start,omitempty"`
}

// PathConditionId defines model for pathConditionId.
type PathConditionId = openapi_types.UUID

// PathPatientId defines model for pathPatientId.
type PathPatientId = openapi_types.UUID

// QueryDate defines model for queryDate.
type QueryDate = openapi_types.Date

// QueryFrom defines model for queryFrom.
type QueryFrom = openapi_types.Date

// QueryPatientId defines model for queryPatientId.
type QueryPatientId = openapi_types.UUID

// QueryTo defines model for queryTo.
type QueryTo = openapi_types.Date

// Conditions defines model for Conditions.
type Conditions struct {
	Conditions []ConditionDisplay `json:"conditions"`
}

// InternalServerErrorResponse Standardized error details (RFC 9457).
type InternalServerErrorResponse = ErrorDetail

// GetConditionsByPatientAndRangeParams defines parameters for GetConditionsByPatientAndRange.
type GetConditionsByPatientAndRangeParams struct {
	// PatientId The unique identifier (UUID) of the patient.
	PatientId QueryPatientId `form:"patientId" json:"patientId"`

	// From The start date (inclusive) for the query range (YYYY-MM-DD format).
	From QueryFrom `form:"from" json:"from"`

	// To The end date (inclusive) for the query range (YYYY-MM-DD format).
	To QueryTo `form:"to" json:"to"`
}

// ConditionsInDateParams defines parameters for ConditionsInDate.
type ConditionsInDateParams struct {
	// Date The specific day (YYYY-MM-DD format).
	Date QueryDate `form:"date" json:"date"`
}

// CreatePatientConditionJSONRequestBody defines body for CreatePatientCondition for application/json ContentType.
type CreatePatientConditionJSONRequestBody = NewCondition

// UpdateConditionJSONRequestBody defines body for UpdateCondition for application/json ContentType.
type UpdateConditionJSONRequestBody = UpdateCondition

// Getter for additional properties for ErrorDetail. Returns the specified
// element and whether it was found
func (a ErrorDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorDetail
func (a *ErrorDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorDetail to handle AdditionalProperties
func (a *ErrorDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorDetail to handle AdditionalProperties
func (a ErrorDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["detail"], err = json.Marshal(a.Detail)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'detail': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetConditionsByPatientAndRange request
	GetConditionsByPatientAndRange(ctx context.Context, params *GetConditionsByPatientAndRangeParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePatientConditionWithBody request with any body
	CreatePatientConditionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePatientCondition(ctx context.Context, body CreatePatientConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConditionsInDate request
	ConditionsInDate(ctx context.Context, patientId PathPatientId, params *ConditionsInDateParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConditionDetail request
	ConditionDetail(ctx context.Context, conditionId PathConditionId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateConditionWithBody request with any body
	UpdateConditionWithBody(ctx context.Context, conditionId PathConditionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateCondition(ctx context.Context, conditionId PathConditionId, body UpdateConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetConditionsByPatientAndRange(ctx context.Context, params *GetConditionsByPatientAndRangeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConditionsByPatientAndRangeRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePatientConditionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePatientConditionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePatientCondition(ctx context.Context, body CreatePatientConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePatientConditionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConditionsInDate(ctx context.Context, patientId PathPatientId, params *ConditionsInDateParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConditionsInDateRequest(c.Server, patientId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConditionDetail(ctx context.Context, conditionId PathConditionId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConditionDetailRequest(c.Server, conditionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateConditionWithBody(ctx context.Context, conditionId PathConditionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateConditionRequestWithBody(c.Server, conditionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCondition(ctx context.Context, conditionId PathConditionId, body UpdateConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateConditionRequest(c.Server, conditionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetConditionsByPatientAndRangeRequest generates requests for GetConditionsByPatientAndRange
func NewGetConditionsByPatientAndRangeRequest(server string, params *GetConditionsByPatientAndRangeParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conditions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "patientId", runtime.ParamLocationQuery, params.PatientId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, params.From); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, params.To); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePatientConditionRequest calls the generic CreatePatientCondition builder with application/json body
func NewCreatePatientConditionRequest(server string, body CreatePatientConditionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePatientConditionRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePatientConditionRequestWithBody generates requests for CreatePatientCondition with any type of body
func NewCreatePatientConditionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conditions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConditionsInDateRequest generates requests for ConditionsInDate
func NewConditionsInDateRequest(server string, patientId PathPatientId, params *ConditionsInDateParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "patientId", runtime.ParamLocationPath, patientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conditions/patient/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date", runtime.ParamLocationQuery, params.Date); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewConditionDetailRequest generates requests for ConditionDetail
func NewConditionDetailRequest(server string, conditionId PathConditionId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "conditionId", runtime.ParamLocationPath, conditionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conditions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateConditionRequest calls the generic UpdateCondition builder with application/json body
func NewUpdateConditionRequest(server string, conditionId PathConditionId, body UpdateConditionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateConditionRequestWithBody(server, conditionId, "application/json", bodyReader)
}

// NewUpdateConditionRequestWithBody generates requests for UpdateCondition with any type of body
func NewUpdateConditionRequestWithBody(server string, conditionId PathConditionId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "conditionId", runtime.ParamLocationPath, conditionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conditions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetConditionsByPatientAndRangeWithResponse request
	GetConditionsByPatientAndRangeWithResponse(ctx context.Context, params *GetConditionsByPatientAndRangeParams, reqEditors ...RequestEditorFn) (*GetConditionsByPatientAndRangeResponse, error)

	// CreatePatientConditionWithBodyWithResponse request with any body
	CreatePatientConditionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePatientConditionResponse, error)

	CreatePatientConditionWithResponse(ctx context.Context, body CreatePatientConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePatientConditionResponse, error)

	// ConditionsInDateWithResponse request
	ConditionsInDateWithResponse(ctx context.Context, patientId PathPatientId, params *ConditionsInDateParams, reqEditors ...RequestEditorFn) (*ConditionsInDateResponse, error)

	// ConditionDetailWithResponse request
	ConditionDetailWithResponse(ctx context.Context, conditionId PathConditionId, reqEditors ...RequestEditorFn) (*ConditionDetailResponse, error)

	// UpdateConditionWithBodyWithResponse request with any body
	UpdateConditionWithBodyWithResponse(ctx context.Context, conditionId PathConditionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateConditionResponse, error)

	UpdateConditionWithResponse(ctx context.Context, conditionId PathConditionId, body UpdateConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateConditionResponse, error)
}

type GetConditionsByPatientAndRangeResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Conditions
	ApplicationproblemJSON400 *ErrorDetail
	ApplicationproblemJSON500 *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetConditionsByPatientAndRangeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConditionsByPatientAndRangeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreatePatientConditionResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON201                   *ConditionDisplay
	ApplicationproblemJSON400 *ErrorDetail
	ApplicationproblemJSON500 *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreatePatientConditionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePatientConditionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConditionsInDateResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Conditions
	ApplicationproblemJSON400 *ErrorDetail
	ApplicationproblemJSON500 *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r ConditionsInDateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConditionsInDateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConditionDetailResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Condition
	ApplicationproblemJSON404 *ErrorDetail
	ApplicationproblemJSON500 *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r ConditionDetailResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConditionDetailResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateConditionResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Condition
	ApplicationproblemJSON400 *ErrorDetail
	ApplicationproblemJSON404 *ErrorDetail
	ApplicationproblemJSON500 *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateConditionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateConditionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetConditionsByPatientAndRangeWithResponse request returning *GetConditionsByPatientAndRangeResponse
func (c *ClientWithResponses) GetConditionsByPatientAndRangeWithResponse(ctx context.Context, params *GetConditionsByPatientAndRangeParams, reqEditors ...RequestEditorFn) (*GetConditionsByPatientAndRangeResponse, error) {
	rsp, err := c.GetConditionsByPatientAndRange(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConditionsByPatientAndRangeResponse(rsp)
}

// CreatePatientConditionWithBodyWithResponse request with arbitrary body returning *CreatePatientConditionResponse
func (c *ClientWithResponses) CreatePatientConditionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePatientConditionResponse, error) {
	rsp, err := c.CreatePatientConditionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePatientConditionResponse(rsp)
}

func (c *ClientWithResponses) CreatePatientConditionWithResponse(ctx context.Context, body CreatePatientConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePatientConditionResponse, error) {
	rsp, err := c.CreatePatientCondition(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePatientConditionResponse(rsp)
}

// ConditionsInDateWithResponse request returning *ConditionsInDateResponse
func (c *ClientWithResponses) ConditionsInDateWithResponse(ctx context.Context, patientId PathPatientId, params *ConditionsInDateParams, reqEditors ...RequestEditorFn) (*ConditionsInDateResponse, error) {
	rsp, err := c.ConditionsInDate(ctx, patientId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConditionsInDateResponse(rsp)
}

// ConditionDetailWithResponse request returning *ConditionDetailResponse
func (c *ClientWithResponses) ConditionDetailWithResponse(ctx context.Context, conditionId PathConditionId, reqEditors ...RequestEditorFn) (*ConditionDetailResponse, error) {
	rsp, err := c.ConditionDetail(ctx, conditionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConditionDetailResponse(rsp)
}

// UpdateConditionWithBodyWithResponse request with arbitrary body returning *UpdateConditionResponse
func (c *ClientWithResponses) UpdateConditionWithBodyWithResponse(ctx context.Context, conditionId PathConditionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateConditionResponse, error) {
	rsp, err := c.UpdateConditionWithBody(ctx, conditionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateConditionResponse(rsp)
}

func (c *ClientWithResponses) UpdateConditionWithResponse(ctx context.Context, conditionId PathConditionId, body UpdateConditionJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateConditionResponse, error) {
	rsp, err := c.UpdateCondition(ctx, conditionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateConditionResponse(rsp)
}

// ParseGetConditionsByPatientAndRangeResponse parses an HTTP response from a GetConditionsByPatientAndRangeWithResponse call
func ParseGetConditionsByPatientAndRangeResponse(rsp *http.Response) (*GetConditionsByPatientAndRangeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConditionsByPatientAndRangeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Conditions
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseCreatePatientConditionResponse parses an HTTP response from a CreatePatientConditionWithResponse call
func ParseCreatePatientConditionResponse(rsp *http.Response) (*CreatePatientConditionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePatientConditionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ConditionDisplay
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseConditionsInDateResponse parses an HTTP response from a ConditionsInDateWithResponse call
func ParseConditionsInDateResponse(rsp *http.Response) (*ConditionsInDateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConditionsInDateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Conditions
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseConditionDetailResponse parses an HTTP response from a ConditionDetailWithResponse call
func ParseConditionDetailResponse(rsp *http.Response) (*ConditionDetailResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConditionDetailResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Condition
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseUpdateConditionResponse parses an HTTP response from a UpdateConditionWithResponse call
func ParseUpdateConditionResponse(rsp *http.Response) (*UpdateConditionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateConditionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Condition
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}
