services:
  api-gateway:
    image: nginx:stable-alpine
    container_name: api-gateway
    ports:
      - "42069:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api-gateway-logs:/var/log/nginx
    networks:
      - medical_network
    restart: unless-stopped
    depends_on:
      - user-service
      - resource-service

  mongo_db:
    image: mongo:7.0-rc
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mysecret
    networks:
      - medical_network

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mysecret
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mexpress
    depends_on:
      - mongo_db
    networks:
      - medical_network

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/local.env
    networks:
      - medical_network
    restart: unless-stopped
    depends_on:
      - mongo_db

  resource-service:
    build:
      context: .
      dockerfile: ./resource-service/Dockerfile
    container_name: resource-service
    env_file:
      - ./resource-service/local.env
    networks:
      - medical_network
    restart: unless-stopped
    depends_on:
      - mongo_db

networks:
  medical_network:
    driver: bridge

volumes:
  db_data: {}
