openapi: 3.0.4
info:
  title: MediCal MicroServices API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags:
  - name: Auth
  - name: Appointments
  - name: Conditions
  - name: Doctors
  - name: Patients
  - name: Resources
  - name: Medical History
servers:
  - description: Cluster Endpoint
    url: /api

paths:
  # User service
  /auth/register:
    $ref: "./paths/auth_register.yaml"
  /auth/login:
    $ref: "./paths/auth_login.yaml"
  /patients/{patientId}:
    $ref: "./paths/patients_patientId.yaml"

  /doctors:
    $ref: "./paths/doctors.yaml"
  /doctors/{doctorId}:
    $ref: "./paths/doctors_doctorId.yaml"

  # Appointments service
  /appointments:
    $ref: "./paths/appointments.yaml"
  /appointments/{appointmentId}:
    $ref: "./paths/appointments_appointmentId.yaml"
  /appointments/patient/{patientId}:
    $ref: "./paths/appointment_patient_patientId.yaml"
  # /appointments/doctor/{doctorId}:
  #   $ref: "./paths/doctors_doctorId_calendar.yaml"
  # /timeslots/{doctorId}:
  #   $ref: "./paths/doctors_doctorId_timeslots.yaml"

  # Conditions service
  /conditions:
    $ref: "./paths/conditions.yaml"
  /conditions/{conditionId}:
    $ref: "./paths/conditions_conditionId.yaml"
  /conditions/patient/{patientId}:
    $ref: "./paths/conditions_patient_patientId.yaml"

  # Prescriptions service
  /prescriptions:
    $ref: "./paths/prescriptions.yaml"
  /prescriptions/{prescriptionId}:
    $ref: "./paths/prescriptions_prescriptionId.yaml"

  # Resources service
  /resources:
    $ref: "./paths/resources.yaml"
  /resources/available:
    $ref: "./paths/resources_available.yaml"
  /resources/{resourceId}:
    $ref: "./paths/resources_resourceId.yaml"
  /resources/reserve/{appointmentId}:
    $ref: "./paths/resources_reserve_appointmentId.yaml"
