openapi: 3.0.4
info:
  title: Auth Service API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - description: Auth Service Endpoint
    url: /
tags:
  - name: Auth
paths:
  /register: # Corresponds to /api/auth/register
    post:
      tags:
        - Auth
      summary: Register a new user
      operationId: registerUser
      requestBody:
        description: User details for registration.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Registration"
      responses:
        "201":
          description: User registered successfully. Returns the created user object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "409":
          description: Conflict - A user with the provided email already exists.
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
              examples:
                duplicateEmail:
                  summary: Example duplicate email error (409)
                  value:
                    title: Conflict
                    status: 409
                    code: user.email-exists
                    detail: A user with email new.patient@example.com already exists.
        "500":
          $ref: "#/components/responses/InternalServerErrorResponse"
  /login: # Corresponds to /api/auth/login
    post:
      tags:
        - Auth
      summary: User Login
      operationId: loginUser
      requestBody:
        description: User credentials for login.
        required: true
        content:
          application/json:
            schema:
              type: object
              title: LoginRequest
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                  example: john.doe@example.com
                role:
                  $ref: "#/components/schemas/UserRole"
              required:
                - email
                - role
            examples:
              patientLogin:
                summary: Example patient login request
                value:
                  email: jane.roe@example.com
                  role: patient
              doctorLogin:
                summary: Example doctor login request
                value:
                  email: dr.house@example.com
                  role: doctor
      responses:
        "200":
          description: Login successful. Sets session cookie or returns token and user details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized - Invalid email or role combination (user not found).
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
              examples:
                invalidCredentials:
                  summary: Example invalid credentials (401)
                  value:
                    title: Unauthorized
                    status: 401
                    code: auth.invalid-credentials
                    detail: No user found with the provided email and role.
        "500":
          $ref: "#/components/responses/InternalServerErrorResponse"

components:
  schemas:
    UserRole:
      type: string
      enum:
        - patient
        - doctor
    PatientRegistration:
      type: object
      required:
        - email
        - firstName
        - lastName
        - role
      properties:
        email:
          type: string
          format: email
          example: new.user@example.com
        firstName:
          type: string
          minLength: 1
          example: John
        lastName:
          type: string
          minLength: 1
          example: Doe
        role:
          $ref: "#/components/schemas/UserRole"
    SpecializationEnum:
      type: string
      description: Medical specialization of a doctor.
      enum:
        - surgeon
        - gastroenterologist
        - pediatrician
        - diagnostician
        - endocrinologist
        - general_practitioner
        - cardiologist
        - dermatologist
        - neurologist
        - oncologist
        - orthopedist
        - psychiatrist
        - radiologist
        - urologist
        - other
      example: diagnostician
    DoctorRegistration:
      allOf:
        - $ref: "#/components/schemas/PatientRegistration"
        - type: object
          properties:
            role:
              $ref: "#/components/schemas/UserRole"
            specialization:
              $ref: "#/components/schemas/SpecializationEnum"
          required:
            - role
            - specialization
    Registration:
      oneOf:
        - $ref: "#/components/schemas/PatientRegistration"
        - $ref: "#/components/schemas/DoctorRegistration"
      discriminator:
        propertyName: role
        mapping:
          patient: "#/components/schemas/PatientRegistration"
          doctor: "#/components/schemas/DoctorRegistration"
    Patient:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - role
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        role:
          $ref: "#/components/schemas/UserRole"
    Doctor:
      allOf:
        - $ref: "#/components/schemas/Patient"
        - type: object
          required:
            - specialization
          properties:
            specialization:
              $ref: "#/components/schemas/SpecializationEnum"
    User:
      oneOf:
        - $ref: "#/components/schemas/Patient"
        - $ref: "#/components/schemas/Doctor"
      discriminator:
        propertyName: role
        mapping:
          patient: "#/components/schemas/Patient"
          doctor: "#/components/schemas/Doctor"
    ErrorDetail:
      type: object
      description: Standardized error details (RFC 9457).
      properties:
        title:
          type: string
        code:
          type: string
        status:
          type: integer
          format: int
        detail:
          type: string
      additionalProperties: true
      required:
        - title
        - code
        - status
        - detail

  responses:
    InternalServerErrorResponse:
      description: An error occurred. See specific status code for details.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ErrorDetail"
          example:
            title: Internal server error
            status: 500
            code: internal.server.error
            detail: An unknown server error occurred
